---
title: "About me"
page-layout: article
title-block-banner: true
---

I received my PhD on talking-face biometric authentication from Telecom ParisTech (France) in 2007.

In 2008, I joined Dublin City University (Ireland) to work on video summarization techniques applied to user-generated content.

I have been a permanent CNRS researcher since 2008:

* at [IRIT](https://www.irit.fr) (Toulouse, France) in the SAMoVA group until 2010
* at [LIMSI](https://www.lisn.upsaclay.fr/) (Orsay, France) in the *Spoken Language Processing* group until 2020
* back at [IRIT](https://www.irit.fr) (Toulouse, France) until today

My current research interests include deep learning techniques applied to machine listening, with a strong focus on speaker diarization: I am proud to be known as *"the guy behind [pyannote](https://www.github.com/pyannote/pyannote-audio)"*.

Since 2021, I propose (paid) scientific [consulting services](consulting.qmd) to companies willing to make the most of their data and open-source speech processing toolkits (and `pyannote` in particular).


## Contact

* Postal Address: IRIT, 118 Route de Narbonne, F-31062 Toulouse, Cedex, France
* Office: IRIT1 219 (2nd floor)
* E-mail: herve.bredin@irit.fr
* Tel: +33 (0)5 61 55 68 86


## Curriculum vitae

### Work experience

#### 2019-today: [Niderb Consulting](consulting.qmd) / Auzeville-Tolosane, France

Scientific consultant. Self-employed.
_Helping companies make the most of their data and open-source speech processing toolkits (and `pyannote` in particular)_

#### 2020-today: [CNRS](https://www.cnrs.fr) / [IRIT](https://www.irit.fr) / Toulouse, France

Research scientist. Member of the SAMoVA team.
_Speaker diarization_

#### 2010-2020: [CNRS](https://www.cnrs.fr) / [LIMSI](https://www.lisn.upsaclay.fr/) (now LISN) / Orsay, France

Research scientist. Member of the TLP team.
_Speaker diarization_

#### 2008-2010: [CNRS](https://www.cnrs.fr) / [IRIT](https://www.irit.fr) / Toulouse, France

Research scientist. Member of the SAMoVA team.
_Content-based video analysis_

#### 2008: [DCU](https://www.dcu.ie) /Dublin, Ireland

Postdoctoral researcher. Member of the CDVP lab. 
_Automatic summarization of user-generated content_

### Education

#### PhD / 2004-2007 / [Télécom Paris](https://www.telecom-paris.fr/) / Paris, France

[Talking-face biometrics](https://www.theses.fr/en/2007ENST0019)

#### MSc / 2001-2004 / [Télécom Paris](https://www.telecom-paris.fr/) / Paris, France

Signal processing and pattern recognition


